name: maseru_marketplace
description: Bilingual Mobile Marketplace for Maseru Taxi Ranks
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  socket_io_client: ^3.1.2
  flutter_dotenv: ^6.0.0
  path_provider: ^2.1.4
  connectivity_plus: ^7.0.0
  pull_to_refresh_flutter3: ^2.0.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  file_picker: ^10.3.3
  permission_handler: ^12.0.1
  # Removed: geolocator: ^12.0.0
  # Removed: google_maps_flutter: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/logo.jpeg